# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

# windowrule = tile,^(Microsoft-edge)$
# windowrule = tile,^(Brave-browser)$
# windowrule = tile,^(Chromium)$
# windowrule = float,^(pavucontrol)$
# windowrule = float,^(blueman-manager)$
#
# windowrulev2 = float,class:(dotfiles-floating)
windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.
windowrulev2 = opacity 1 0.9, class:.* # You'll probably like this.
windowrulev2 = opacity 0.9 0.85,class:^(Alacritty)$
windowrule = tile,^(ONLYOFFICE Desktop Editors)$
