-- Monitors
-- (Legacy monitors.conf was generated by nwg-displays, which writes hyprlang.
--  nwg-displays cannot write Lua, so update this file by hand or re-translate
--  monitors.conf after running nwg-displays. See notes from the conversion.)

hl.monitor({ output = "DP-3",     mode = "1920x1080@100", position = "1920x0", scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@100", position = "0x0",    scale = 1 })
