-- Workspaces
-- (Legacy workspaces.conf was generated by nwg-displays, which writes hyprlang.
--  nwg-displays cannot write Lua, so maintain this file by hand.)

hl.workspace_rule({ workspace = "1",  monitor = "HDMI-A-1", default = true })
hl.workspace_rule({ workspace = "2",  monitor = "DP-3",     default = true })
hl.workspace_rule({ workspace = "3",  monitor = "DP-3" })
hl.workspace_rule({ workspace = "4",  monitor = "DP-3" })
hl.workspace_rule({ workspace = "5",  monitor = "DP-3" })
hl.workspace_rule({ workspace = "6",  monitor = "DP-3" })
hl.workspace_rule({ workspace = "7",  monitor = "DP-3" })
hl.workspace_rule({ workspace = "8",  monitor = "DP-3" })
hl.workspace_rule({ workspace = "9",  monitor = "DP-3" })
hl.workspace_rule({ workspace = "10", monitor = "DP-3" })
