-- Auto-generated by apply_theme.sh - DO NOT EDIT
-- Returns a table of color strings consumed by config/general.lua
return {
    bg             = "rgb(000000)",
    bgAlt          = "rgb(1E1E1E)",
    fg             = "rgb(D4D4D4)",
    fgBright       = "rgb(FFFFFF)",
    accent         = "rgb(1793d0)",
    border         = "rgba(404040FF)",
    borderActive   = "rgba(1793d0FF)",
    borderInactive = "rgba(404040FF)",
    red            = "rgb(F44747)",
    green          = "rgb(4EC9B0)",
    yellow         = "rgb(D7BA7D)",
    blue           = "rgb(569CD6)",
    magenta        = "rgb(C586C0)",
    cyan           = "rgb(4EC9B0)",
    orange         = "rgb(CE9178)",
    warning        = "rgb(fabd2f)",
    critical       = "rgb(F44747)",
    selection      = "rgb(264F78)",
}
