# windowrule = tile,^(Microsoft-edge)$
# windowrule = tile,^(Brave-browser)$
# windowrule = tile,^(Chromium)$
windowrule = float,^(pavucontrol)$
# windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrulev2 = stayfocused,class:(Rofi)
# windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.
windowrulev2 = opacity 1 0.9, class:.* # You'll probably like this.
windowrulev2 = opacity 0.9 0.85,class:^(Alacritty)$
windowrule = tile,^(ONLYOFFICE Desktop Editors)$
# windowrule = tile,^(jetbrains-studio)$
windowrulev2=nofocus,class:^jetbrains-(?!toolbox),floating:1,title:^win\d+$
