# Auto-generated by apply_theme.sh - DO NOT EDIT
set --global fish_color_normal D4D4D4
set --global fish_color_command 569CD6
set --global fish_color_param 4EC9B0
set --global fish_color_quote D7BA7D
set --global fish_color_redirection 4EC9B0 --bold
set --global fish_color_end 4EC9B0
set --global fish_color_error F14C4C
set --global fish_color_comment 808080
set --global fish_color_autosuggestion 666666
set --global fish_color_operator 29B8DB
set --global fish_color_escape 29B8DB
set --global fish_color_cwd 4EC9B0
set --global fish_color_cwd_root F44747
set --global fish_color_user B5CEA8
set --global fish_color_host D4D4D4
set --global fish_color_host_remote D7BA7D
set --global fish_color_cancel -r
set --global fish_color_search_match FFFFFF --background=3E3E3E
set --global fish_color_selection FFFFFF --bold --background=3E3E3E
set --global fish_color_status F44747
set --global fish_color_valid_path --underline
set --global fish_color_history_current --bold
set --global fish_pager_color_completion D4D4D4
set --global fish_pager_color_description D7BA7D -i
set --global fish_pager_color_prefix D4D4D4 --bold --underline
set --global fish_pager_color_progress FFFFFF --background=4EC9B0
set --global fish_pager_color_selected_background -r
