#!/bin/bash

# ============================================
# Centralized Theme Applier
# Reads colors.conf and generates per-tool
# color files that each config sources/imports
# ============================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COLORS_FILE="$SCRIPT_DIR/colors.conf"
CONFIG_DIR="$HOME/.config"

# -----------------------------------------------------
# Parse colors.conf into variables
# -----------------------------------------------------
declare -A C
while IFS='=' read -r key value; do
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    C[$key]="$value"
done < "$COLORS_FILE"

# Helper: strip # from hex
hex() { echo "${C[$1]#\#}"; }
# Helper: full hex with #
h() { echo "${C[$1]}"; }

echo "Applying theme from $COLORS_FILE..."

# -----------------------------------------------------
# 1. HYPR - config/colors.conf
# -----------------------------------------------------
cat > "$CONFIG_DIR/hypr/config/colors.conf" << EOF
# Auto-generated by apply_theme.sh - DO NOT EDIT
\$colorBg = rgb($(hex bg))
\$colorBgAlt = rgb($(hex bg_alt))
\$colorFg = rgb($(hex fg))
\$colorFgBright = rgb($(hex fg_bright))
\$colorAccent = rgb($(hex accent))
\$colorBorder = rgba($(hex border)FF)
\$colorBorderActive = rgba($(hex accent)FF)
\$colorBorderInactive = rgba($(hex border)FF)
\$colorRed = rgb($(hex red))
\$colorGreen = rgb($(hex green))
\$colorYellow = rgb($(hex yellow))
\$colorBlue = rgb($(hex blue))
\$colorMagenta = rgb($(hex magenta))
\$colorCyan = rgb($(hex cyan))
\$colorOrange = rgb($(hex orange))
\$colorWarning = rgb($(hex warning))
\$colorCritical = rgb($(hex critical))
\$colorSelection = rgb($(hex bg_selection))
EOF
echo "  [OK] hypr/config/colors.conf"

# -----------------------------------------------------
# 2. WAYBAR - colors.css
# -----------------------------------------------------
cat > "$CONFIG_DIR/waybar/colors.css" << EOF
/* Auto-generated by apply_theme.sh - DO NOT EDIT */
@define-color bg $(h bg);
@define-color bg-alt $(h bg_alt);
@define-color bg-light $(h bg_light);
@define-color bg-lighter $(h bg_lighter);
@define-color bg-hover $(h bg_hover);
@define-color fg $(h fg);
@define-color fg-muted $(h fg_muted);
@define-color fg-bright $(h fg_bright);
@define-color accent $(h accent);
@define-color red $(h red);
@define-color green $(h green);
@define-color yellow $(h yellow);
@define-color blue $(h blue);
@define-color magenta $(h magenta);
@define-color cyan $(h cyan);
@define-color orange $(h orange);
@define-color warning $(h warning);
@define-color critical $(h critical);
@define-color border-color $(h border);
@define-color selection $(h bg_selection);
@define-color success $(h success);
EOF
echo "  [OK] waybar/colors.css"

# -----------------------------------------------------
# 3. TMUX - colors.conf
# -----------------------------------------------------
cat > "$CONFIG_DIR/tmux/colors.conf" << EOF
# Auto-generated by apply_theme.sh - DO NOT EDIT
set -g @theme_bg_dark '$(h bg)'
set -g @theme_bg_medium '$(h bg_alt)'
set -g @theme_bg_light '$(h bg_light)'
set -g @theme_bg_lighter '$(h bg_lighter)'
set -g @theme_fg_default '$(h fg)'
set -g @theme_fg_muted '$(h fg_muted)'
set -g @theme_accent_blue '$(h blue)'
set -g @theme_accent_blue_dark '$(h bg_selection)'
set -g @theme_accent_cyan '$(h bright_blue)'
set -g @theme_accent_yellow '$(h bright_yellow)'
set -g @theme_message_bg '$(h yellow)'
EOF
echo "  [OK] tmux/colors.conf"

# -----------------------------------------------------
# 4. NVIM - lua/config/colors.lua
# -----------------------------------------------------
cat > "$CONFIG_DIR/nvim/lua/config/colors.lua" << EOF
-- Auto-generated by apply_theme.sh - DO NOT EDIT
return {
  bg = "$(h bg)",
  bg_alt = "$(h bg_alt)",
  bg_light = "$(h bg_light)",
  bg_lighter = "$(h bg_lighter)",
  bg_selection = "$(h bg_selection)",
  bg_hover = "$(h bg_hover)",
  fg = "$(h fg)",
  fg_muted = "$(h fg_muted)",
  fg_bright = "$(h fg_bright)",
  fg_dim = "$(h fg_dim)",
  red = "$(h red)",
  green = "$(h green)",
  yellow = "$(h yellow)",
  blue = "$(h blue)",
  magenta = "$(h magenta)",
  cyan = "$(h cyan)",
  orange = "$(h orange)",
  bright_red = "$(h bright_red)",
  bright_green = "$(h bright_green)",
  bright_yellow = "$(h bright_yellow)",
  bright_blue = "$(h bright_blue)",
  bright_magenta = "$(h bright_magenta)",
  bright_cyan = "$(h bright_cyan)",
  border = "$(h border)",
  border_active = "$(h border_active)",
  warning = "$(h warning)",
  critical = "$(h critical)",
  success = "$(h success)",
}
EOF
echo "  [OK] nvim/lua/config/colors.lua"

# -----------------------------------------------------
# 5. KITTY - themes/theme.conf
# -----------------------------------------------------
cat > "$CONFIG_DIR/kitty/themes/theme.conf" << EOF
# Auto-generated by apply_theme.sh - DO NOT EDIT
background $(h bg)
foreground $(h fg)
cursor $(h fg_bright)
selection_background $(h bg_selection)
selection_foreground $(h fg_bright)
url_color $(h cyan)

color0  $(h bg_alt)
color1  $(h red)
color2  $(h green)
color3  $(h yellow)
color4  $(h blue)
color5  $(h magenta)
color6  $(h cyan)
color7  $(h fg)
color8  $(h bg_lighter)
color9  $(h bright_red)
color10 $(h bright_green)
color11 $(h orange)
color12 $(h bright_blue)
color13 $(h bright_magenta)
color14 $(h bright_cyan)
color15 $(h fg_bright)
EOF
echo "  [OK] kitty/themes/theme.conf"

# -----------------------------------------------------
# 6. ROFI - colors.rasi
# -----------------------------------------------------
cat > "$CONFIG_DIR/rofi/colors.rasi" << EOF
/* Auto-generated by apply_theme.sh - DO NOT EDIT */
* {
    background:     $(h bg)FF;
    background-alt: $(h bg_alt)FF;
    foreground:     $(h fg)FF;
    selected:       $(h accent);
    active:         $(h green)FF;
    urgent:         $(h red)FF;
    red:            $(h red)FF;
    green:          $(h green)FF;
    yellow:         $(h yellow)FF;
    blue:           $(h blue)FF;
    magenta:        $(h magenta)FF;
    cyan:           $(h cyan)FF;
    border:         $(h accent)FF;
}
EOF
echo "  [OK] rofi/colors.rasi"

# -----------------------------------------------------
# 7. FISH - conf.d/theme_colors.fish
# -----------------------------------------------------
cat > "$CONFIG_DIR/fish/conf.d/theme_colors.fish" << EOF
# Auto-generated by apply_theme.sh - DO NOT EDIT
set --global fish_color_normal $(hex fg)
set --global fish_color_command $(hex blue)
set --global fish_color_param $(hex cyan)
set --global fish_color_quote $(hex yellow)
set --global fish_color_redirection $(hex cyan) --bold
set --global fish_color_end $(hex green)
set --global fish_color_error $(hex bright_red)
set --global fish_color_comment $(hex fg_muted)
set --global fish_color_autosuggestion $(hex fg_dim)
set --global fish_color_operator $(hex bright_cyan)
set --global fish_color_escape $(hex bright_cyan)
set --global fish_color_cwd $(hex green)
set --global fish_color_cwd_root $(hex red)
set --global fish_color_user $(hex bright_green)
set --global fish_color_host $(hex fg)
set --global fish_color_host_remote $(hex yellow)
set --global fish_color_cancel -r
set --global fish_color_search_match $(hex fg_bright) --background=$(hex bg_lighter)
set --global fish_color_selection $(hex fg_bright) --bold --background=$(hex bg_lighter)
set --global fish_color_status $(hex red)
set --global fish_color_valid_path --underline
set --global fish_color_history_current --bold
set --global fish_pager_color_completion $(hex fg)
set --global fish_pager_color_description $(hex yellow) -i
set --global fish_pager_color_prefix $(hex fg) --bold --underline
set --global fish_pager_color_progress $(hex fg_bright) --background=$(hex cyan)
set --global fish_pager_color_selected_background -r
EOF
echo "  [OK] fish/conf.d/theme_colors.fish"

# -----------------------------------------------------
# 8. YAZI - theme.toml colors section
# Already uses vscode-dark-modern flavor, no override needed
# -----------------------------------------------------
echo "  [OK] yazi (uses vscode-dark flavor, no changes needed)"

echo ""
echo "Theme applied! To take effect:"
echo "  - Hypr:   config auto-reloads"
echo "  - Waybar: SUPER+SHIFT+B"
echo "  - Tmux:   prefix + r"
echo "  - Nvim:   :source \$MYVIMRC"
echo "  - Kitty:  ctrl+shift+f5"
echo "  - Rofi:   next launch"
echo "  - Fish:   new shell or: source ~/.config/fish/conf.d/theme_colors.fish"
